[package]
name = "snake"
version = "0.2.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
rand = "0.9.0"
lazy_static = "1.5.0"
winit = "0.30.9"
wasm-bindgen-futures = "0.4.50"
tracing = "0.1.41"